### ISSUE TITLE
Not compatible with Cypress version 4.1.0?

### ISSUE THREAD

**Issue by bvanderneut** [bahmutov/cypress-skip-and-only-ui#172]
Hello,

Can it be that the plugin is not compatible with the newest cypress version?
I see other icons (double) and they do not interact like it should be. See this link for an example:
https://www.flickr.com/photos/bjornvanderneut/49654680176/

Hope this plugin get's into the Cypress core it self because it would be extremely usefull.

Bye,
Bjorn

**Comment by LeJeanbono** [comment]
Same in 4.2.0.
A `undefined` is put in the test file

**Comment by pablorsk** [comment]
Same in 4.3.0.
Just work with 4.0.*
