### ISSUE TITLE
Not seeing UI buttons with Cypress 5.0

### ISSUE THREAD

**Issue by KatieMFritz** [bahmutov/cypress-skip-and-only-ui#233]
I'm just installing this, and I'm not seeing any buttons in my Cypress UI. Related to #93 probably.

## What I did:

1. Installed 1.2.7 as a dev dependency and updated my Cypress config as shared below.
2. Restarted Cypress UI.
3. Ran all specs until they were finished.
4. Ran one spec with failing tests.

My UI for a failing test looks like this:
<img width="538" alt="Screen Shot 2020-08-21 at 2 08 50 PM" src="https://user-images.githubusercontent.com/7085184/90921346-13915280-e3b8-11ea-999c-eb661adf718c.png">

## Config files
```js
// support/index.js
require('cypress-skip-and-only-ui/support')
```

```js
// plugins /index.js
const dotenvPlugin = require('cypress-dotenv')
const task = require('cypress-skip-and-only-ui/task')

module.exports = (on, config) => {
    // Cypress skip and only UI
    on('task', task)

  // Load environment variables from .env file
    config = dotenvPlugin(config, { path: '../../.env' }, true)

  // Allow overriding baseUrl from an environment variable
    const baseUrl = config.env.DEFAULT_SITE_URL || null
    if (baseUrl) {
        config.baseUrl = baseUrl
    }
    return config
}
```
Cypress.json (not changed, but in case it helps)
```json
{
  "baseUrl": "[localUrl]",
  "integrationFolder": "cypress/integration/[myfolder]",
  "chromeWebSecurity": false,
  "nodeVersion": "system",
  "projectId": "[id]",
  "retries": 2
}
```

**Comment by dmitry** [comment]
Any ideas what is the alternative option to the cypress-skip-and-only-ui plugin and using `it.only` (I'm quite often forgetting to remove `.only` from specs before commit).

**Comment by tmartin2089** [comment]
Same, Cypress 5.x and there are no buttons.

**Comment by Light07** [comment]
Is there any plan to get this plugin up to date?

**Comment by bahmutov** [comment]
I would welcome external help to add the buttons back in.

**Comment by feliperaul** [comment]
My git history is littered with "remove .only" commits, lol. I'd love to get this back.

**Comment by bahmutov** [comment]
Could be due to test retries?
