### ISSUE TITLE
Buttons are not working on Cypress v8.3.x

### ISSUE THREAD

**Issue by jakecastelli** [bahmutov/cypress-skip-and-only-ui#406]
I am on Cypress version `8.3.1` and `1.2.12` for this plugin.

The bug is that I can see those three buttons next to each test, but when I click on any of them, it does nothing.

https://user-images.githubusercontent.com/38635403/140513018-a8597972-8d5e-4316-8e39-2e650ef746a8.mov

**Comment by hotdogdragon** [comment]
@jakecastelli Can you check your plugins/index.js file?
You need to register the three plugin tasks.
Example:

```js
const { downloadFile } = require('cypress-downloadfile/lib/addPlugin');
const { onlyTests, skipTests, allTests } = require('cypress-skip-and-only-ui/task');

module.exports = function (on, config) {
  on('task', { onlyTests, skipTests, allTests, downloadFile });
};
```

**Comment by jakecastelli** [comment]
Hi @hotdogdragon thanks for the reply.

I have followed the README and all the required setup. Unfortunately it is still not working as the video shows above, I can see the buttons, but when I click on them nothing happens.

**Comment by jakecastelli** [comment]
When I click on the button, there is an warning / error:
```
Unhandled rejection CypressError: `cy.task('skipTests')` failed with the following error:> Unexpected token (17:18) 
   at ${my host address}/__cypress/runner/cypress_runner.js:158874:78From previous event:    
   at Context.task (${my host address}/runner/cypress_runner.js:158856:15)From Your Spec Code:
   at onClickSkip (${my host address}/__cypress/tests?p=cypress/support/index.ts:1958:12)

**Comment by jakecastelli** [comment]
to update this, I found after you click on the button, you will need to click rerun test or press `r` then it will work, I don't think that's what it is original behaviour but it is just a workaround for now.

**Comment by jakecastelli** [comment]
Probably duplicated of #227
