### ISSUE TITLE
Not sure if actually working

### ISSUE THREAD

**Issue by tomardern** [bahmutov/cypress-skip-and-only-ui#66]
Hi.

I've just installed this now, and not totally sure this is working as expected.

![image](https://user-images.githubusercontent.com/1135454/59677395-a1284f80-91c1-11e9-8330-f5a96b2ca64c.png)

- We're seeing the icons here, but clicking on them just opens/closes the test
- We only see the icons once a test has run successfully.

Any ideas?

**Comment by archigo** [comment]
I have successfully installed and used the buttons today.

**Comment by tomardern** [comment]
Ah - I wasn't aware that this would change the underlying test files.

Thanks for clarification.
