### ISSUE TITLE
Multiple tasks

### ISSUE THREAD

**Issue by dialex** [bahmutov/cypress-skip-and-only-ui#93]
I tried following the README but I think I have an issue with multiple tasks.
Actually, I'm using your other plugin [select-tests](https://github.com/bahmutov/cypress-select-tests), so my `plugins/index.js` looks like this:

```js
const selectTestsWithGrep = require("cypress-select-tests/grep")
const task = require("cypress-skip-and-only-ui/task")

module.exports = async (on, config) => {
  on("task", task) //this compiles and runs, but I don't have the skip buttons on UI
  on("file:preprocessor", selectTestsWithGrep(config))

  (...)
  return config
}
```

Do you know what I'm doing wrong?

**Comment by dialex** [comment]
Ok, I think I know what the problem was: **you need to run at least one time the full suite, and then the buttons appear**. I assumed the buttons were always there -- like I could start Cypress, run all, stop all, then select, then rerun.

In reality you need to start Cypress, run all, wait for it to finish, then select, then rerun.

**Comment by mtuzinskiy** [comment]
The buttons don't appear for me even if I run the full suite...

**Comment by pablorsk** [comment]
@mtuzinskiy downgrade to `cypress ~4.0.0`. (https://github.com/bahmutov/cypress-skip-and-only-ui/issues/172#issuecomment-607951264)
